services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8812:8812"
    volumes:
      - ./uploads:/app/backend/uploads
      - ./static:/app/backend/static
      - .:/app/backend
    environment:
      - MYSQL_SERVER=192.168.110.73
      - MYSQL_USER=comic
      - MYSQL_PASSWORD=YyzK2jPEaTKKAhjs
      - MYSQL_DB=comic
    restart: always

volumes:
  mysql_data: